insert into treinador(nome, idade, cidade) values('thiago',9,'pelotas');
insert into box(tipo_ambiente, num_suportado, id_prof, id_treinador) values('praia',78,1,1);
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(1,'masterball',2,1);
insert into pokemon(nivel_felicidade, nivel, hp) values(83,30,42);
insert into ataque(tipo, ccuracy, dano) values('psychic',36,14);
insert into tem(id_pokemon, id_ataque) values(1,1);
insert into ataque(tipo, ccuracy, dano) values('light',43,40);
insert into tem(id_pokemon, id_ataque) values(1,2);
insert into evolução2(id_pokemon, peso, nome, CP, tipo2) values(1,80,'mew',1577,'mewtwo');
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(1,'masterball',2,1);
insert into pokemon(nivel_felicidade, nivel, hp) values(79,17,57);
insert into ataque(tipo, ccuracy, dano) values('dark',51,62);
insert into tem(id_pokemon, id_ataque) values(2,3);
insert into ataque(tipo, ccuracy, dano) values('dark',45,31);
insert into tem(id_pokemon, id_ataque) values(2,4);
insert into evolução3(id_pokemon, peso, nome, CP, tipo2) values(2,23,'gastly',837,'haunter');
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(1,'pokeballl',2,1);
insert into pokemon(nivel_felicidade, nivel, hp) values(80,32,73);
insert into ataque(tipo, ccuracy, dano) values('thunder',80,81);
insert into tem(id_pokemon, id_ataque) values(3,5);
insert into ataque(tipo, ccuracy, dano) values('normal',88,75);
insert into tem(id_pokemon, id_ataque) values(3,6);
insert into evolução2(id_pokemon, peso, nome, CP, tipo2) values(3,46,'pikachu',335,'raichu');
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(1,'greatball',2,1);
insert into pokemon(nivel_felicidade, nivel, hp) values(19,29,17);
insert into ataque(tipo, ccuracy, dano) values('grass',12,16);
insert into tem(id_pokemon, id_ataque) values(4,7);
insert into ataque(tipo, ccuracy, dano) values('bug',30,6);
insert into tem(id_pokemon, id_ataque) values(4,8);
insert into evolução1(id_pokemon, peso, nome, CP) values(4,25,'bulbassaur',1285);
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(1,'pokeball',2,1);
insert into pokemon(nivel_felicidade, nivel, hp) values(84,55,54);
insert into ataque(tipo, ccuracy, dano) values('bug',41,6);
insert into tem(id_pokemon, id_ataque) values(5,9);
insert into ataque(tipo, ccuracy, dano) values('bug',15,37);
insert into tem(id_pokemon, id_ataque) values(5,10);
insert into evolução2(id_pokemon, peso, nome, CP, tipo2) values(5,82,'caterpie',1611,'metapod');
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(0,'pokeball',2,1);
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(1,'greatball',2,1);
insert into pokemon(nivel_felicidade, nivel, hp) values(76,14,42);
insert into ataque(tipo, ccuracy, dano) values('fight',48,45);
insert into tem(id_pokemon, id_ataque) values(6,11);
insert into ataque(tipo, ccuracy, dano) values('fight',74,35);
insert into tem(id_pokemon, id_ataque) values(6,12);
insert into evolução3(id_pokemon, peso, nome, CP, tipo2) values(6,81,'hitmonlee',1132,'nope');
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(1,'pokeball',2,1);
insert into pokemon(nivel_felicidade, nivel, hp) values(6,51,60);
insert into ataque(tipo, ccuracy, dano) values('ghost',22,14);
insert into tem(id_pokemon, id_ataque) values(7,13);
insert into ataque(tipo, ccuracy, dano) values('ghost',28,51);
insert into tem(id_pokemon, id_ataque) values(7,14);
insert into evolução2(id_pokemon, peso, nome, CP, tipo2) values(7,35,'gengar',328,'null');
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(1,'masterball',2,1);
insert into pokemon(nivel_felicidade, nivel, hp) values(56,18,34);
insert into ataque(tipo, ccuracy, dano) values('thunder',61,10);
insert into tem(id_pokemon, id_ataque) values(8,15);
insert into ataque(tipo, ccuracy, dano) values('normal',91,75);
insert into tem(id_pokemon, id_ataque) values(8,16);
insert into evolução3(id_pokemon, peso, nome, CP, tipo2) values(8,30,'zapdos',1609,'null');
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(1,'masterball',2,1);
insert into pokemon(nivel_felicidade, nivel, hp) values(56,5,74);
insert into ataque(tipo, ccuracy, dano) values('ice',49,4);
insert into tem(id_pokemon, id_ataque) values(9,17);
insert into ataque(tipo, ccuracy, dano) values('water',18,22);
insert into tem(id_pokemon, id_ataque) values(9,18);
insert into evolução1(id_pokemon, peso, nome, CP) values(9,89,'articuno',55);
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(1,'masterball',2,1);
insert into pokemon(nivel_felicidade, nivel, hp) values(22,47,5);
insert into ataque(tipo, ccuracy, dano) values('fire',33,20);
insert into tem(id_pokemon, id_ataque) values(10,19);
insert into ataque(tipo, ccuracy, dano) values('fire',71,60);
insert into tem(id_pokemon, id_ataque) values(10,20);
insert into evolução3(id_pokemon, peso, nome, CP, tipo2) values(10,89,'moltres',1394,'null');
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(1,'pokeball',2,1);
insert into pokemon(nivel_felicidade, nivel, hp) values(50,96,64);
insert into ataque(tipo, ccuracy, dano) values('pigdey',35,56);
insert into tem(id_pokemon, id_ataque) values(11,21);
insert into ataque(tipo, ccuracy, dano) values('flying',73,26);
insert into tem(id_pokemon, id_ataque) values(11,22);
insert into evolução1(id_pokemon, peso, nome, CP) values(11,71,'rattata',1607);
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(1,'greatball',2,1);
insert into pokemon(nivel_felicidade, nivel, hp) values(91,26,12);
insert into ataque(tipo, ccuracy, dano) values('fkying',16,27);
insert into tem(id_pokemon, id_ataque) values(12,23);
insert into ataque(tipo, ccuracy, dano) values('flying',15,33);
insert into tem(id_pokemon, id_ataque) values(12,24);
insert into evolução3(id_pokemon, peso, nome, CP, tipo2) values(12,5,'spearow',474,'fearow');
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(1,'masterball',2,1);
insert into pokemon(nivel_felicidade, nivel, hp) values(54,26,20);
insert into ataque(tipo, ccuracy, dano) values('fire',59,58);
insert into tem(id_pokemon, id_ataque) values(13,25);
insert into ataque(tipo, ccuracy, dano) values('fire',39,81);
insert into tem(id_pokemon, id_ataque) values(13,26);
insert into evolução1(id_pokemon, peso, nome, CP) values(13,61,'entei',69);
insert into box(tipo_ambiente, num_suportado, id_prof, id_treinador) values('campo',82,1,1);
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(0,'pokeball',3,1);
insert into treinador(nome, idade, cidade) values('ash',62,'pallet');
insert into box(tipo_ambiente, num_suportado, id_prof, id_treinador) values('caverna',36,1,2);
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(1,'pokeball',4,2);
insert into pokemon(nivel_felicidade, nivel, hp) values(26,97,72);
insert into ataque(tipo, ccuracy, dano) values('poison',51,74);
insert into tem(id_pokemon, id_ataque) values(14,27);
insert into ataque(tipo, ccuracy, dano) values('normal',54,21);
insert into tem(id_pokemon, id_ataque) values(14,28);
insert into evolução2(id_pokemon, peso, nome, CP, tipo2) values(14,96,'zubat',1198,'golbat');
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(1,'greatball',4,2);
insert into pokemon(nivel_felicidade, nivel, hp) values(43,11,24);
insert into ataque(tipo, ccuracy, dano) values('grass',58,96);
insert into tem(id_pokemon, id_ataque) values(15,29);
insert into ataque(tipo, ccuracy, dano) values('bug',24,62);
insert into tem(id_pokemon, id_ataque) values(15,30);
insert into evolução1(id_pokemon, peso, nome, CP) values(15,77,'paras',739);
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(1,'pokeball',4,2);
insert into pokemon(nivel_felicidade, nivel, hp) values(40,87,96);
insert into ataque(tipo, ccuracy, dano) values('ground',30,67);
insert into tem(id_pokemon, id_ataque) values(16,31);
insert into ataque(tipo, ccuracy, dano) values('ground',65,43);
insert into tem(id_pokemon, id_ataque) values(16,32);
insert into evolução2(id_pokemon, peso, nome, CP, tipo2) values(16,28,'sandshrew',504,'sandslash');
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(1,'nidoranm',4,2);
insert into pokemon(nivel_felicidade, nivel, hp) values(52,5,52);
insert into ataque(tipo, ccuracy, dano) values('nidoranf',75,55);
insert into tem(id_pokemon, id_ataque) values(17,33);
insert into ataque(tipo, ccuracy, dano) values('poison',77,29);
insert into tem(id_pokemon, id_ataque) values(17,34);
insert into evolução2(id_pokemon, peso, nome, CP, tipo2) values(17,57,'nidorina',424,'nidoqueen');
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(1,'masterball',4,2);
insert into pokemon(nivel_felicidade, nivel, hp) values(25,51,35);
insert into ataque(tipo, ccuracy, dano) values('ground',48,8);
insert into tem(id_pokemon, id_ataque) values(18,35);
insert into ataque(tipo, ccuracy, dano) values('ground',82,71);
insert into tem(id_pokemon, id_ataque) values(18,36);
insert into evolução3(id_pokemon, peso, nome, CP, tipo2) values(18,50,'geodude',700,'graveler');
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(1,'ultraball',4,2);
insert into pokemon(nivel_felicidade, nivel, hp) values(59,41,86);
insert into ataque(tipo, ccuracy, dano) values('griund',7,70);
insert into tem(id_pokemon, id_ataque) values(19,37);
insert into ataque(tipo, ccuracy, dano) values('ground',53,71);
insert into tem(id_pokemon, id_ataque) values(19,38);
insert into evolução3(id_pokemon, peso, nome, CP, tipo2) values(19,40,'golem',350,'null');
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(1,'greatball',4,2);
insert into pokemon(nivel_felicidade, nivel, hp) values(68,91,7);
insert into ataque(tipo, ccuracy, dano) values('fire',19,17);
insert into tem(id_pokemon, id_ataque) values(20,39);
insert into ataque(tipo, ccuracy, dano) values('fire',13,48);
insert into tem(id_pokemon, id_ataque) values(20,40);
insert into evolução1(id_pokemon, peso, nome, CP) values(20,40,'ponyta',956);
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(1,'ultraball',4,2);
insert into pokemon(nivel_felicidade, nivel, hp) values(21,64,6);
insert into ataque(tipo, ccuracy, dano) values('fire',7,63);
insert into tem(id_pokemon, id_ataque) values(21,41);
insert into ataque(tipo, ccuracy, dano) values('fire',66,88);
insert into tem(id_pokemon, id_ataque) values(21,42);
insert into evolução3(id_pokemon, peso, nome, CP, tipo2) values(21,86,'rapidash',689,'null');
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(1,'greatball',4,2);
insert into pokemon(nivel_felicidade, nivel, hp) values(85,97,29);
insert into ataque(tipo, ccuracy, dano) values('water',70,3);
insert into tem(id_pokemon, id_ataque) values(22,43);
insert into ataque(tipo, ccuracy, dano) values('psychic',50,22);
insert into tem(id_pokemon, id_ataque) values(22,44);
insert into evolução2(id_pokemon, peso, nome, CP, tipo2) values(22,14,'slowpoke',961,'slowbro');
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(1,'greatball',4,2);
insert into pokemon(nivel_felicidade, nivel, hp) values(27,81,3);
insert into ataque(tipo, ccuracy, dano) values('eletric',33,51);
insert into tem(id_pokemon, id_ataque) values(23,45);
insert into ataque(tipo, ccuracy, dano) values('steel',20,97);
insert into tem(id_pokemon, id_ataque) values(23,46);
insert into evolução1(id_pokemon, peso, nome, CP) values(23,16,'magnemite',836);
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(1,'pokeball',4,2);
insert into pokemon(nivel_felicidade, nivel, hp) values(53,36,51);
insert into ataque(tipo, ccuracy, dano) values('normal',11,94);
insert into tem(id_pokemon, id_ataque) values(24,47);
insert into ataque(tipo, ccuracy, dano) values('flying',66,76);
insert into tem(id_pokemon, id_ataque) values(24,48);
insert into evolução2(id_pokemon, peso, nome, CP, tipo2) values(24,51,'farfetchd',213,'null');
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(1,'ultraball',4,2);
insert into pokemon(nivel_felicidade, nivel, hp) values(69,87,9);
insert into ataque(tipo, ccuracy, dano) values('ice',49,8);
insert into tem(id_pokemon, id_ataque) values(25,49);
insert into ataque(tipo, ccuracy, dano) values('water',63,51);
insert into tem(id_pokemon, id_ataque) values(25,50);
insert into evolução2(id_pokemon, peso, nome, CP, tipo2) values(25,40,'seel',164,'dewgong');
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(1,'greatball',4,2);
insert into pokemon(nivel_felicidade, nivel, hp) values(94,66,96);
insert into ataque(tipo, ccuracy, dano) values('poison',97,50);
insert into tem(id_pokemon, id_ataque) values(26,51);
insert into ataque(tipo, ccuracy, dano) values('poison',46,68);
insert into tem(id_pokemon, id_ataque) values(26,52);
insert into evolução2(id_pokemon, peso, nome, CP, tipo2) values(26,96,'grimmer',635,'muk');
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(1,'greatball',4,2);
insert into pokemon(nivel_felicidade, nivel, hp) values(34,100,23);
insert into ataque(tipo, ccuracy, dano) values('water',84,10);
insert into tem(id_pokemon, id_ataque) values(27,53);
insert into ataque(tipo, ccuracy, dano) values('water',16,49);
insert into tem(id_pokemon, id_ataque) values(27,54);
insert into evolução2(id_pokemon, peso, nome, CP, tipo2) values(27,49,'shellder',1751,'cloyster');
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(1,'ultraball',4,2);
insert into pokemon(nivel_felicidade, nivel, hp) values(50,69,89);
insert into ataque(tipo, ccuracy, dano) values('rock',10,70);
insert into tem(id_pokemon, id_ataque) values(28,55);
insert into ataque(tipo, ccuracy, dano) values('ground',97,25);
insert into tem(id_pokemon, id_ataque) values(28,56);
insert into evolução2(id_pokemon, peso, nome, CP, tipo2) values(28,30,'steelix',1364,'null');
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(1,'pokeball',4,2);
insert into pokemon(nivel_felicidade, nivel, hp) values(83,23,81);
insert into ataque(tipo, ccuracy, dano) values('psychic',78,71);
insert into tem(id_pokemon, id_ataque) values(29,57);
insert into ataque(tipo, ccuracy, dano) values('psychic',30,75);
insert into tem(id_pokemon, id_ataque) values(29,58);
insert into evolução2(id_pokemon, peso, nome, CP, tipo2) values(29,27,'drowzee',522,'hypno');
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(1,'greatball',4,2);
insert into pokemon(nivel_felicidade, nivel, hp) values(25,60,22);
insert into ataque(tipo, ccuracy, dano) values('water',99,44);
insert into tem(id_pokemon, id_ataque) values(30,59);
insert into ataque(tipo, ccuracy, dano) values('normal',83,14);
insert into tem(id_pokemon, id_ataque) values(30,60);
insert into evolução2(id_pokemon, peso, nome, CP, tipo2) values(30,72,'krabby',1814,'kingler');
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(1,'ultraball',4,2);
insert into pokemon(nivel_felicidade, nivel, hp) values(47,21,83);
insert into ataque(tipo, ccuracy, dano) values('wlwtric',35,30);
insert into tem(id_pokemon, id_ataque) values(31,61);
insert into ataque(tipo, ccuracy, dano) values('eletric',52,83);
insert into tem(id_pokemon, id_ataque) values(31,62);
insert into evolução1(id_pokemon, peso, nome, CP) values(31,23,'voltorb',612);
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(1,'greatball',4,2);
insert into pokemon(nivel_felicidade, nivel, hp) values(69,5,35);
insert into ataque(tipo, ccuracy, dano) values('grass',49,34);
insert into tem(id_pokemon, id_ataque) values(32,63);
insert into ataque(tipo, ccuracy, dano) values('normal',57,30);
insert into tem(id_pokemon, id_ataque) values(32,64);
insert into evolução3(id_pokemon, peso, nome, CP, tipo2) values(32,47,'exeggcute',1957,'exeggutor');
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(1,'ultraball',4,2);
insert into pokemon(nivel_felicidade, nivel, hp) values(82,71,16);
insert into ataque(tipo, ccuracy, dano) values('ground',55,21);
insert into tem(id_pokemon, id_ataque) values(33,65);
insert into ataque(tipo, ccuracy, dano) values('ground',59,37);
insert into tem(id_pokemon, id_ataque) values(33,66);
insert into evolução2(id_pokemon, peso, nome, CP, tipo2) values(33,55,'cubone',1460,'marowak');
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(1,'greatball',4,2);
insert into pokemon(nivel_felicidade, nivel, hp) values(100,1,80);
insert into ataque(tipo, ccuracy, dano) values('normal',34,87);
insert into tem(id_pokemon, id_ataque) values(34,67);
insert into ataque(tipo, ccuracy, dano) values('psychic',62,37);
insert into tem(id_pokemon, id_ataque) values(34,68);
insert into evolução3(id_pokemon, peso, nome, CP, tipo2) values(34,67,'licktung',559,'licklicky');
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(0,'masterball',4,2);
insert into box(tipo_ambiente, num_suportado, id_prof, id_treinador) values('misty',52,1,2);
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(1,'loveball',5,2);
insert into pokemon(nivel_felicidade, nivel, hp) values(36,15,19);
insert into ataque(tipo, ccuracy, dano) values('water',36,48);
insert into tem(id_pokemon, id_ataque) values(35,69);
insert into ataque(tipo, ccuracy, dano) values('water',76,66);
insert into tem(id_pokemon, id_ataque) values(35,70);
insert into evolução2(id_pokemon, peso, nome, CP, tipo2) values(35,22,'horsea',622,'seadra');
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(1,'pokeball',5,2);
insert into pokemon(nivel_felicidade, nivel, hp) values(40,44,37);
insert into ataque(tipo, ccuracy, dano) values('bug',94,64);
insert into tem(id_pokemon, id_ataque) values(36,71);
insert into ataque(tipo, ccuracy, dano) values('bug',48,83);
insert into tem(id_pokemon, id_ataque) values(36,72);
insert into evolução3(id_pokemon, peso, nome, CP, tipo2) values(36,54,'odish',942,'gloom');
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(1,'ultraball',5,2);
insert into pokemon(nivel_felicidade, nivel, hp) values(48,54,74);
insert into ataque(tipo, ccuracy, dano) values('fairy',33,92);
insert into tem(id_pokemon, id_ataque) values(37,73);
insert into ataque(tipo, ccuracy, dano) values('fairy',35,69);
insert into tem(id_pokemon, id_ataque) values(37,74);
insert into evolução3(id_pokemon, peso, nome, CP, tipo2) values(37,53,'clefairy',1127,'clefable');
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(1,'greatball',5,2);
insert into pokemon(nivel_felicidade, nivel, hp) values(46,88,93);
insert into ataque(tipo, ccuracy, dano) values('water',64,24);
insert into tem(id_pokemon, id_ataque) values(38,75);
insert into ataque(tipo, ccuracy, dano) values('fight',92,91);
insert into tem(id_pokemon, id_ataque) values(38,76);
insert into evolução2(id_pokemon, peso, nome, CP, tipo2) values(38,51,'psyduck',612,'golduck');
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(1,'greatball',5,2);
insert into pokemon(nivel_felicidade, nivel, hp) values(14,90,55);
insert into ataque(tipo, ccuracy, dano) values('fight',50,84);
insert into tem(id_pokemon, id_ataque) values(39,77);
insert into ataque(tipo, ccuracy, dano) values('rock',70,49);
insert into tem(id_pokemon, id_ataque) values(39,78);
insert into evolução3(id_pokemon, peso, nome, CP, tipo2) values(39,19,'machop',1954,'machoke');
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(1,'pokeball',5,2);
insert into pokemon(nivel_felicidade, nivel, hp) values(59,18,59);
insert into ataque(tipo, ccuracy, dano) values('grass',32,51);
insert into tem(id_pokemon, id_ataque) values(40,79);
insert into ataque(tipo, ccuracy, dano) values('poison',51,18);
insert into tem(id_pokemon, id_ataque) values(40,80);
insert into evolução2(id_pokemon, peso, nome, CP, tipo2) values(40,63,'bellsprout',571,'weepinbell');
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(0,'greatball',5,2);
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(0,'greatball',5,2);
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(1,'greatball',5,2);
insert into pokemon(nivel_felicidade, nivel, hp) values(98,8,10);
insert into ataque(tipo, ccuracy, dano) values('water',42,24);
insert into tem(id_pokemon, id_ataque) values(41,81);
insert into ataque(tipo, ccuracy, dano) values('water',85,34);
insert into tem(id_pokemon, id_ataque) values(41,82);
insert into evolução1(id_pokemon, peso, nome, CP) values(41,25,'tentacool',184);
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(1,'masterball',5,2);
insert into pokemon(nivel_felicidade, nivel, hp) values(78,38,73);
insert into ataque(tipo, ccuracy, dano) values('normal',84,40);
insert into tem(id_pokemon, id_ataque) values(42,83);
insert into ataque(tipo, ccuracy, dano) values('normal',8,54);
insert into tem(id_pokemon, id_ataque) values(42,84);
insert into evolução1(id_pokemon, peso, nome, CP) values(42,77,'doduo',624);
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(1,'pokeball',5,2);
insert into pokemon(nivel_felicidade, nivel, hp) values(94,36,41);
insert into ataque(tipo, ccuracy, dano) values('grass',52,19);
insert into tem(id_pokemon, id_ataque) values(43,85);
insert into ataque(tipo, ccuracy, dano) values('normal',43,54);
insert into tem(id_pokemon, id_ataque) values(43,86);
insert into evolução3(id_pokemon, peso, nome, CP, tipo2) values(43,14,'tangela',1717,'null');
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(1,'greatball',5,2);
insert into pokemon(nivel_felicidade, nivel, hp) values(59,63,76);
insert into ataque(tipo, ccuracy, dano) values('bug',68,4);
insert into tem(id_pokemon, id_ataque) values(44,87);
insert into ataque(tipo, ccuracy, dano) values('bug',51,53);
insert into tem(id_pokemon, id_ataque) values(44,88);
insert into evolução2(id_pokemon, peso, nome, CP, tipo2) values(44,17,'scyther',477,'scizor');
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(1,'pokeball',5,2);
insert into pokemon(nivel_felicidade, nivel, hp) values(20,94,67);
insert into ataque(tipo, ccuracy, dano) values('water',45,29);
insert into tem(id_pokemon, id_ataque) values(45,89);
insert into ataque(tipo, ccuracy, dano) values('water',6,4);
insert into tem(id_pokemon, id_ataque) values(45,90);
insert into evolução3(id_pokemon, peso, nome, CP, tipo2) values(45,97,'goldeen',1381,'seaking');
insert into treinador(nome, idade, cidade) values('angela',57,'lavander');
insert into box(tipo_ambiente, num_suportado, id_prof, id_treinador) values('cemiterio',109,1,3);
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(1,'greatball',6,3);
insert into pokemon(nivel_felicidade, nivel, hp) values(68,50,94);
insert into ataque(tipo, ccuracy, dano) values('ghost',86,92);
insert into tem(id_pokemon, id_ataque) values(46,91);
insert into ataque(tipo, ccuracy, dano) values('ghost',99,74);
insert into tem(id_pokemon, id_ataque) values(46,92);
insert into evolução3(id_pokemon, peso, nome, CP, tipo2) values(46,15,'gastly',1032,'haunter');
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(1,'greatball',6,3);
insert into pokemon(nivel_felicidade, nivel, hp) values(67,43,52);
insert into ataque(tipo, ccuracy, dano) values('normal',71,45);
insert into tem(id_pokemon, id_ataque) values(47,93);
insert into ataque(tipo, ccuracy, dano) values('normal',4,59);
insert into tem(id_pokemon, id_ataque) values(47,94);
insert into evolução2(id_pokemon, peso, nome, CP, tipo2) values(47,32,'cubone',631,'marowak');
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(1,'greatball',6,3);
insert into pokemon(nivel_felicidade, nivel, hp) values(6,98,27);
insert into ataque(tipo, ccuracy, dano) values('normal',87,55);
insert into tem(id_pokemon, id_ataque) values(48,95);
insert into ataque(tipo, ccuracy, dano) values('normal',30,20);
insert into tem(id_pokemon, id_ataque) values(48,96);
insert into evolução3(id_pokemon, peso, nome, CP, tipo2) values(48,62,'magikarp',477,'gyarados');
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(1,'greatball',6,3);
insert into pokemon(nivel_felicidade, nivel, hp) values(93,29,78);
insert into ataque(tipo, ccuracy, dano) values('normal',38,67);
insert into tem(id_pokemon, id_ataque) values(49,97);
insert into ataque(tipo, ccuracy, dano) values('normal',69,37);
insert into tem(id_pokemon, id_ataque) values(49,98);
insert into evolução1(id_pokemon, peso, nome, CP) values(49,26,'eevee',1203);
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(1,'masterball',6,3);
insert into pokemon(nivel_felicidade, nivel, hp) values(24,44,45);
insert into ataque(tipo, ccuracy, dano) values('normal',75,66);
insert into tem(id_pokemon, id_ataque) values(50,99);
insert into ataque(tipo, ccuracy, dano) values('normal',42,30);
insert into tem(id_pokemon, id_ataque) values(50,100);
insert into evolução1(id_pokemon, peso, nome, CP) values(50,2,'snorlax',461);
insert into box(tipo_ambiente, num_suportado, id_prof, id_treinador) values('praia',26,1,3);
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(1,'pokeball',7,3);
insert into pokemon(nivel_felicidade, nivel, hp) values(60,59,33);
insert into ataque(tipo, ccuracy, dano) values('normal',46,65);
insert into tem(id_pokemon, id_ataque) values(51,101);
insert into ataque(tipo, ccuracy, dano) values('normal',62,65);
insert into tem(id_pokemon, id_ataque) values(51,102);
insert into evolução2(id_pokemon, peso, nome, CP, tipo2) values(51,76,'tauros',1893,'null');
insert into treinador(nome, idade, cidade) values('telmo',9,'pelotas');
insert into box(tipo_ambiente, num_suportado, id_prof, id_treinador) values('neve',23,1,4);
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(1,'pokeball',8,4);
insert into pokemon(nivel_felicidade, nivel, hp) values(70,46,22);
insert into ataque(tipo, ccuracy, dano) values('rock',91,34);
insert into tem(id_pokemon, id_ataque) values(52,103);
insert into ataque(tipo, ccuracy, dano) values('water',14,16);
insert into tem(id_pokemon, id_ataque) values(52,104);
insert into evolução2(id_pokemon, peso, nome, CP, tipo2) values(52,89,'kabuto',211,'kabutops');
insert into treinador(nome, idade, cidade) values('marcelinho',33,'sãopaulo');
insert into box(tipo_ambiente, num_suportado, id_prof, id_treinador) values('canil',34,1,5);
insert into pokebola(ocupada, tipo, id_box, id_treinador) values(1,'greatball',9,5);
insert into pokemon(nivel_felicidade, nivel, hp) values(77,74,44);
insert into ataque(tipo, ccuracy, dano) values('fire',53,28);
insert into tem(id_pokemon, id_ataque) values(53,105);
insert into ataque(tipo, ccuracy, dano) values('fire',4,59);
insert into tem(id_pokemon, id_ataque) values(53,106);
insert into evolução1(id_pokemon, peso, nome, CP) values(53,14,'growlithe',1891);
